networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.32.0.0/16

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quorum-backend
    tty: true
    ports:
      - "8080:8080"
    environment:
      "COMPOSE_BAKE": "true"
      "RETRAIN": "false"
    volumes:
      - ".:/app"
    networks:
      default:
        ipv4_address: 172.32.0.4

  frontend:
    build:
      context: .
      dockerfile: containers/frontend/Dockerfile
    container_name: quorum-frontend
    tty: true
    ports:
      - "8000:8000"
    environment:
      "COMPOSE_BAKE": "true"
      "RETRAIN": "false"
    volumes:
      - .:/app
      - /app/frontend/node_modules
    networks:
      default:
        ipv4_address: 172.32.0.5
